baseURL: ""
languageCode: en-us
title: Chaitanya Chawak
pagination:
  disableAliases: true
  pagerSize: 2
  path: page
theme: PaperMod


params:
  #homeInfoParams:
  #  Title: "Hello there !"
  #  Content: This is my new website
  
  ShowBreadCrumbs: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: /teacup_nobg.png
    #favicon16x16: /teacup_nobg.png
    #favicon32x32: /teacup_nobg.png

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Chaitanya Chawak
    subtitle: "Hello there."
    extrainfo: "I am Chaitanya Chawak, a Research Engineer in the [Cosmostat lab](https://www.cosmostat.org/) at [CEA Paris-Saclay](https://www.cea.fr/). My interests include (but are not limited to) Machine Learning, Astrophysics, software development and learning cool new stuff. In my free time, I like to listen to music, solve puzzles, and [sleep](/calvin-sleeping-through-bedtime.jpg)."
    extraextrainfo: "I'm usually up for fun discussions anytime, so feel free to contact me via any of my socials !"
    imageUrl: me.jpeg
    imageWidth: 200
    imageHeight: 200
    imageTitle: its a me !

  socialIcons:
    - name: github
      url: "https://github.com/ChaitanyaChawak"
    - name: Twitter
      url: "https://twitter.com/chaitanyachawak"
    - name: Discord
      url: "https://discordapp.com/users/Chai#8995"
    - name: email
      url: "mailto:chaitanya.chawak@cea.fr"


menu:
  main:
    - identifier: home
      name: Home
      url: ""
      weight: 1
    - identifier: academics
      name: Academics
      url: /academics/
      weight: 5
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 10
    #- identifier: archives
    #  name: Archives
    #  url: /archives/
    #  weight: 15
    - identifier: mylogs
      name: My Logs
      url: /mylogs/
      weight: 15
    - identifier: misc
      name: Misc
      url: /misc/
      weight: 20
    #- identifier: tags
    #  name: Tags
    #  url: /tags/
    #  weight: 25

